### ISSUE TITLE
Unable to self host with reverse proxy

### ISSUE THREAD

**Issue by viasux** [wukko/cobalt#248]
Been trying to set this up with docker-compose as shown in the guide.

Here are my config files. The server returns a 502 error. My dns records are set up. Uncommenting the first port line throws another error as well.

docker-compose.yml:
```
version: '3.5'

services:
    cobalt-api:
        image: ghcr.io/wukko/cobalt:latest
        restart: unless-stopped
        container_name: cobalt-api

        init: true

        # if container doesn't run detached on your machine, uncomment the next line:
        #tty: true

        ports:
            #- 9000:9000/tcp
            # if you're using a reverse proxy, uncomment the next line:
            - 127.0.0.1:9000:9000

        environment:
            - apiPort=9000
            # replace apiURL with your instance's target url in same format
            - apiURL=https://coapi.redacted.com/
            # replace apiName with your instance's distinctive name
            - apiName=eu-nl
            # if you want to use cookies when fetching data from services, uncomment the next line
            #- cookiePath=/cookies.json
            # see cookies_example.json for example file.
        labels:
            - com.centurylinklabs.watchtower.scope=cobalt

        # if you want to use cookies when fetching data from services, uncomment volumes and next line
        #volumes:
            #- ./cookies.json:/cookies.json

    cobalt-web:
        image: ghcr.io/wukko/cobalt:latest
        restart: unless-stopped
        container_name: cobalt-web

        init: true

        # if container doesn't run detached on your machine, uncomment the next line:
        #tty: true

        ports:
            #- 9001:9001/tcp
            # if you're using a reverse proxy, uncomment the next line:
            - 127.0.0.1:9001:9001

        environment:
            - webPort=9001
            # replace webURL with your instance's target url in same format
            - webURL=https://co.redacted.com/
            # replace apiURL with preferred api instance url
            - apiURL=https://coapi.redacted.com/

        labels:
            - com.centurylinklabs.watchtower.scope=cobalt

    # update the cobalt image automatically with watchtower
    watchtower:
        image: ghcr.io/containrrr/watchtower
        restart: unless-stopped
        command: --cleanup --scope cobalt --interval 900
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
```

caddyfile
```
co.redacted.com {
  reverse_proxy 127.0.0.1:9001
}

coapi.redacted.com {
  reverse_proxy 127.0.0.1:9000
}
```

**Comment by dumbmoron** [comment]
could you check whether the Cobalt instance is running by accessing it directly (for example via curl on the server:  `curl localhost:9000`)

**Comment by viasux** [comment]
> could you check whether the cobalt instance is running by accessing it directly (for example via curl on the server: `curl localhost:9000`)?

looks like it isn't

also docker ps is showing it restart looping

**Comment by dumbmoron** [comment]
that's strange, could you share the logs of the container? (`docker logs cobalt-api`)

**Comment by wukko** [comment]
you commented out ports, cobalt can't access them, therefore it throws an error and docker restarts it in loop:

![image](https://github.com/wukko/cobalt/assets/71202418/2f210def-a831-409f-b906-b11e393cd2b3)

**Comment by wukko** [comment]
if the problem is solved, close the issue

**Comment by Sevenanths** [comment]
I ignored the documentation because I too was having issues, and just experimented until I got things working with my own reverse proxy set-up. My pointers:

- Even if you're using a reverse proxy, **do not uncomment the "reverse proxy" lines**. It'll cause a double bind for ports 9000 or 9001, after which the Docker containers no longer start.
- Do not change "apiPort" or "webPort" to 443, like I intuitively did (my proxy runs over https). You'd think these need to reflect the ports of the reverse proxy, but they don't. Keep them on 9000 and 9001 respectively.
- For the instance URLs, you *can* use your full reverse proxy URLs.

Hope this helps!

**Comment by wukko** [comment]
> I ignored the documentation

well, you shouldn't have! i made a tutorial based on what i do myself to host main instances. uncommenting "reverse proxy" lines does NOT cause double binding, it's done to prevent exposing ports outside of a reverse proxy of choice.

**Comment by Sevenanths** [comment]
Ah, well, see, I'm simply not familiar with that syntax. I guess I have to change the IP address to the address of my proxy? Please add this to the documentation for those who might not know (like me!).

Other documentation regarding the exact meaning of variables like "apiPort" and "webPort" (what perspective?) would be welcome as well. In any case, I just wanted to share how I got cobalt running, should others be confused :-).

**Comment by viasux** [comment]
> you commented out ports, cobalt can't access them, therefore it throws an error and docker restarts it in loop:
> 
> ![image](https://private-user-images.githubusercontent.com/71202418/284106773-2f210def-a831-409f-b906-b11e393cd2b3.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzOTYxMjYsIm5iZiI6MTcwMTM5NTgyNiwicGF0aCI6Ii83MTIwMjQxOC8yODQxMDY3NzMtMmYyMTBkZWYtYTgzMS00MDlmLWI5MDYtYjExZTM5M2NkMmIzLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQwMTU3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWM3NGQ1MzExYmZjZmFhZDlhZjkxNzZkYTYzNTYzOTVjMjM4ZWJlMmRmYzczZTQzYmJmOTQ5Yzg1NTM1NmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NNy470lmU44whEt1aw4FTayV3Nwe1S_TWAk3RlR6I2I)
> 
> _screenshot for api config, but web config also has the same issue_

I'm pretty sure I only did that as a troubleshooting step, but ill try uncommenting it next time i have some free time.

**Comment by albertopasqualetto** [comment]
Also for me it doesn't work if I uncomment that line.
Error:
```
Error response from daemon: driver failed programming external connectivity on endpoint cobalt-api (1bc2b19f912a54a75159288860e0f7bcb090c668848085f22b264083fe56c51c): Error starting userland proxy: listen tcp4 0.0.0.0:9000: bind: address already in use
```
It works otherwise.

**Comment by wukko** [comment]
> Also for me it doesn't work if I uncomment that line.

do you happen to have something else running at 9000 port? error suggests that, so i just wanna make sure.

**Comment by albertopasqualetto** [comment]
> > Also for me it doesn't work if I uncomment that line.
> 
> do you happen to have something else running at 9000 port? error suggests that, so i just wanna make sure.

I did a `netstat | grep 9000` and nothing showed up.

If I does not uncomment that line, then it works.

**Comment by wukko** [comment]
> If I does not uncomment that line, then it works.

could you reply with a screenshot/extract of your current docker compose config?

**Comment by albertopasqualetto** [comment]
@wukko 

```
services:
# COBALT
  cobalt-api:
    image: ghcr.io/wukko/cobalt:7
    restart: unless-stopped
    container_name: cobalt-api
    init: true
    ports:
      - 9000:9000/tcp
      # if you're using a reverse proxy, uncomment the next line:
      # - 127.0.0.1:9000:9000
      # - 9000:9000
    environment:
      # replace apiURL with your instance's target url in same format
      - apiURL=https://cobaltapi.mydomain.duckdns.org/
      # replace apiName with your instance's distinctive name
      - apiName=eu-mi
      # if you want to use cookies when fetching data from services, uncomment the next line
      #- cookiePath=/cookies.json
      # see cookies_example.json for example file.
    # if you want to use cookies when fetching data from services, uncomment volumes and next line
    #volumes:
        #- ./cookies.json:/cookies.json
    networks:
      - cobalt
      - caddy
    labels:
      caddy: cobaltapi.mydomain.duckdns.org
      caddy.reverse_proxy: "{{upstreams 9000}}"
  cobalt-web:
    image: ghcr.io/wukko/cobalt:7
    restart: unless-stopped
    container_name: cobalt-web
    init: true
    ports:
      - 9001:9001/tcp
      # if you're using a reverse proxy, uncomment the next line:
      # - 127.0.0.1:9001:9001
      # - 9001:9001
    environment:
      # replace webURL with your instance's target url in same format
      - webURL=https://dl.mydomain.duckdns.org/
      # replace apiURL with preferred api instance url
      - apiURL=https://cobaltapi.mydomain.duckdns.org/
    depends_on:
      - cobalt-api
    networks:
      - cobalt
      - caddy
    labels:
      caddy: dl.mydomain.duckdns.org
      caddy.reverse_proxy: "{{upstreams 9001}}"
```
