### ISSUE TITLE
Unable to download instagram stories with self-hosted cobalt

### ISSUE THREAD

**Issue by MiraiSubject** [wukko/cobalt#435]
**bug description**
When trying to download any instagram story (n=3) the error: "it seems like this service is not supported yet or your link is invalid. have you pasted the right link?" shows up in the self-hosted version of cobalt.

Example URL that does not work (as of posting story is 6h old): https://www.instagram.com/stories/sega/3348105858019674311/

<details><summary>Docker compose file</summary>
<p>

```yaml
version: "3.5"
services:
  cobalt-api:
    image: ghcr.io/wukko/cobalt:7
    restart: unless-stopped
    container_name: cobalt-api
    init: true
    # if container doesn't run detached on your machine, uncomment the next line
    #tty: true

    ports:
      - 9000:9000/tcp
      # if you're using a reverse proxy, uncomment the next line and remove the one above (9000:9000/tcp):
      #- 127.0.0.1:9000:9000

    environment:
      # replace https://co.wuk.sh/ with your instance's target url in same format
      API_URL: http://myhostname.local:9000/
      # replace eu-nl with your instance's distinctive name
      API_NAME: myhostname
      # see docs/run-an-instance.md for more information
    labels:
      - com.centurylinklabs.watchtower.scope=cobalt
      # - ./cookies.json:/cookies.json
  cobalt-web:
    image: ghcr.io/wukko/cobalt:7
    restart: unless-stopped
    container_name: cobalt-web
    init: true
    # if container doesn't run detached on your machine, uncomment the next line
    #tty: true

    ports:
      - 9001:9001/tcp
      # if you're using a reverse proxy, uncomment the next line and remove the one above (9001:9001/tcp):
      #- 127.0.0.1:9001:9001

    environment:
      # replace https://cobalt.tools/ with your instance's target url in same format
      WEB_URL: https://myhostname.local:9001/ # replace https://co.wuk.sh/ with preferred api instance url
      API_URL: http://myhostname.local:9000/
    labels:
      - com.centurylinklabs.watchtower.scope=cobalt
  # update the cobalt image automatically with watchtower
  watchtower:
    image: ghcr.io/containrrr/watchtower
    restart: unless-stopped
    command: --cleanup --scope cobalt --interval 900
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks: {}
```

</p>
</details> 

**reproduction steps**
steps to reproduce the behavior:
1. Deploy the container using the above docker compose file
2. Paste the story URL and click the arrows to download
3. Observe: 
![CleanShot 2024-04-17 at 18 11 19](https://github.com/wukko/cobalt/assets/803255/efa85c7a-c05a-45a5-b000-86f3fc60fcf2)

**screenshots**

**links**
https://www.instagram.com/stories/sega/3348105858019674311/
https://www.instagram.com/stories/heyitssharla/3348111419970427324/

**platform**
- Server OS: Debian / DIetPi 9.3.1
- Client OS: macOS Sonoma
- Browser: Safari & Firefox 125

**additional context**
Downloading the stories does work from https://cobalt.tools/

I also made sure to run `docker compose pull` and `docker compose up -d` to ensure I have the latest version based on that the instagram endpoints got changed: https://github.com/wukko/cobalt/commit/6d17ff2e06120626cb88fb55622a0f1e26c71bf3

![CleanShot 2024-04-17 at 18 16 42](https://github.com/wukko/cobalt/assets/803255/b0dfb31b-b532-4a84-85ac-629d95136762)

Also downloading images and reels still work as expected.
